alertmanager:
  alertmanagerSpec:
    config:
      global:
        smtp_smarthost: 'smtp.gmail.com:587'
        smtp_from: 'rodol.giacomodonatto@gmail.com'
        smtp_auth_username: 'rodol.giacomodonatto@gmail.com'
        smtp_auth_password: 'zowgmvhpjbfgtpoy'
        smtp_require_tls: true

      route:
        receiver: 'email-notifications'
        group_by: [ 'alertname' ]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 1h

      receivers:
        - name: 'email-notifications'
          email_configs:
            - to: 'rodol.giacomodonatto@gmail.com'
              send_resolved: true

prometheus:
  prometheusSpec:
    alerting:
      alertmanagers:
        - namespace: monitoring
          name: alertmanager-operated
          port: http-web
    ruleSelector:
      matchLabels:
        role: prometheus-rulefiles