apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert
  namespace: monitoring
  labels:
    role: prometheus-rulefiles
spec:
  groups:
    - name: test-alert-group
      rules:
        - alert: TestAlert
          expr: vector(1)
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "This is a test alert"
            description: "This alert is to test the email notification configuration"
